### ISSUE TITLE
pb with angular 

### ISSUE THREAD

**Issue by roox80** [jibeetz/podcast-webapp#1]
Hello ,

i test to lauch this projet and i have an error with angular, finaly i find in Gruntfile.js this line is comment : 

'bower_components/angular-soundmanager2/dist/angular-soundmanager2.min.js',

this point in a repo not exist in our git name angular-soundmanager2 i search and find this git https://github.com/perminder-klair/angular-soundmanager2 i have change in bower.json the ref of your git by this git and the project load the main page 

Best regards,

Simon

**Comment by jibeetz** [comment]
Hi,

Thanks for noticing, this dependency was actually useless as it was directly included (and customized) in the project, (/app/src/js/lib/angular-soundmanager2.js), so I removed its reference in the bower file.
